## Import Library

In [2]:
import torch
print(torch.__version__)

2.9.1+cpu


## Create Tensor

In [25]:
# From List

t1=torch.tensor([1,2,3,4,5,6])
print(t1)
print()
t2=torch.tensor([[1,2,3],[5,6,2]])
print(t2)

tensor([1, 2, 3, 4, 5, 6])

tensor([[1, 2, 3],
        [5, 6, 2]])


In [41]:
# Zeros Tensor

t3=torch.zeros(3,5)
print(t3)
print()

# Ones Tensor

t4=torch.ones(3,5)
print(t4)
print()

# Tensor with Specific Values

t5=torch.full((3,5),4)
print(t5)
print()

# Random Tensor
t6=torch.rand(3,5)
print(t6)
print()

t7=torch.randint(1,10,(3,5))
print(t7)
print()

torch.manual_seed(100)    # Manual seed to generate tensor randomly but same every time
t8=torch.rand(2,4)
print(t8)
print()
torch.manual_seed(100)
t9=torch.rand(2,4)
print(t9)
print()

# empty tensor

t9=torch.empty(2,4)
print(t9)
print()

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

tensor([[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]])

tensor([[0.2080, 0.1180, 0.1217, 0.7356, 0.7118],
        [0.7876, 0.4183, 0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784, 0.8238, 0.5557]])

tensor([[1, 2, 4, 7, 4],
        [7, 8, 8, 6, 7],
        [9, 3, 7, 7, 4]])

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

tensor([[0.1117, 0.8158, 0.2626, 0.4839],
        [0.6765, 0.7539, 0.2627, 0.0428]])

tensor([[4.6102e-40, 7.9874e-43, 2.6256e-01, 4.8388e-01],
        [6.7650e-01, 7.5391e-01, 2.6269e-01, 4.2840e-02]])



In [40]:
# arange
print(torch.arange(0,10,2))

# using linspace
print(torch.linspace(0,10,10))

# using eye
print(torch.eye(5))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [46]:
# Specify Data Type

t1=torch.full((2,4),7,dtype=torch.float32)
print(t1)
print()

t2=torch.eye(2,3,dtype=float)
t2

tensor([[7., 7., 7., 7.],
        [7., 7., 7., 7.]])



tensor([[1., 0., 0.],
        [0., 1., 0.]], dtype=torch.float64)

In [53]:
# Convert Datatype

a=torch.rand(2,5,dtype=torch.float32)
print(a.dtype)

a= a.to(torch.int32)
print(a.dtype)

torch.float32
torch.int32


In [ ]:
# Keeps same shape

a = torch.rand(2, 2)

zeros_like = torch.zeros_like(a)
ones_like = torch.ones_like(a)


In [42]:
# Tensor Properties

a=torch.full((4,5),7)

print(a.shape)
print(a.dtype)
print(type(a))

torch.Size([4, 5])
torch.int64
<class 'torch.Tensor'>


In [122]:
# NumPy → PyTorch

import numpy as np

a=np.array([1,2,3,4,5])
b=torch.from_numpy(a)
print(b)

# PyTorch → NumPy

a=torch.tensor([1,2,3,4,5])
b=a.numpy()
print(b)


tensor([1, 2, 3, 4, 5])
[1 2 3 4 5]


## Mathematical operations

In [56]:
x=torch.full((4,5),7)

# addition
print(x + 2)
print()

# substraction
print(x - 2)
print()

# multiplication
print(x * 2)
print()

# division
print(x / 2)
print()

# int division
print((x * 100)//3)
print

# mod
((x * 100)//3)%2
# power
x**2

tensor([[9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9],
        [9, 9, 9, 9, 9]])

tensor([[5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5],
        [5, 5, 5, 5, 5]])

tensor([[14, 14, 14, 14, 14],
        [14, 14, 14, 14, 14],
        [14, 14, 14, 14, 14],
        [14, 14, 14, 14, 14]])

tensor([[3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000],
        [3.5000, 3.5000, 3.5000, 3.5000, 3.5000]])

tensor([[233, 233, 233, 233, 233],
        [233, 233, 233, 233, 233],
        [233, 233, 233, 233, 233],
        [233, 233, 233, 233, 233]])


tensor([[49, 49, 49, 49, 49],
        [49, 49, 49, 49, 49],
        [49, 49, 49, 49, 49],
        [49, 49, 49, 49, 49]])

In [58]:
c = torch.tensor([1, -2, 3, -4])

# abs
print(torch.abs(c))
print()

# Negative
print(torch.neg(c))
print()

d = torch.tensor([1.9, 2.3, 3.7, 4.4])

# round
print(torch.round(d))
print()

# Ceil
print(torch.ceil(d))
print()

# Floor
print(torch.floor(d))
print()

tensor([1, 2, 3, 4])

tensor([-1,  2, -3,  4])

tensor([2., 2., 4., 4.])

tensor([2., 3., 4., 5.])

tensor([1., 2., 3., 4.])



In [ ]:
# Clamp

d=torch.tensor([1,2,3,4,5,6,7,8])
d= d.clamp(min=3,max=7)
print(d)

tensor([3, 3, 3, 4, 5, 6, 7, 7])


## Reduction operation

In [62]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 4., 7.],
        [2., 3., 8.]])

In [68]:
# sum
print(torch.sum(e))
print()

# sum columnwise
print(torch.sum(e,dim=0))

# sum rowwise
print(torch.sum(e,dim=1))

tensor(32.)

tensor([10.,  7., 15.])
tensor([19., 13.])


In [ ]:
# mean
print(torch.mean(e))
# mean along col
print(torch.mean(e, dim=0))
# mean along row
print(torch.mean(e,dim=1))

tensor(5.3333)
tensor([5.0000, 3.5000, 7.5000])
tensor([6.3333, 4.3333])


In [74]:
# median
print("Median:-",torch.median(e))

# max and min
print("Max:-",torch.max(e))
print("Min:-",torch.min(e))

# product
print("Product:-",torch.prod(e))

# standard deviation
print("Standard Deviation: ",torch.std(e))

# variance
print("Varience:-",torch.var(e))

# argmax
print(torch.argmax(e))

# argmin
print(torch.argmin(e))

Median:- tensor(4.)
Max:- tensor(8.)
Min:- tensor(2.)
Product:- tensor(10752.)
Standard Deviation:  tensor(2.6583)
Varience:- tensor(7.0667)
tensor(0)
tensor(3)


## Matrix operations

In [75]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 6, 2],
        [9, 5, 0]])
tensor([[4, 2],
        [7, 1],
        [1, 5]])


In [76]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[64, 26],
        [71, 23]])

In [77]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [81]:
# transpose
torch.transpose(f,0,1)

tensor([[5, 9],
        [6, 5],
        [2, 0]])

In [82]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[4., 4., 1.],
        [1., 2., 4.],
        [7., 2., 5.]])

In [83]:
# determinant
torch.det(h)

tensor(88.)

In [84]:
# inverse
torch.inverse(h)

tensor([[ 0.0227, -0.2045,  0.1591],
        [ 0.2614,  0.1477, -0.1705],
        [-0.1364,  0.2273,  0.0455]])

## Comparison operations

In [85]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[6, 1, 4],
        [5, 6, 9]])
tensor([[2, 3, 1],
        [0, 2, 1]])


In [86]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

## Special functions

In [87]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 7., 9.],
        [2., 4., 6.]])

In [90]:
# log
print(torch.log(k))
print

#sqrt
print(torch.sqrt(h))
print()

# sigmod
print(torch.sigmoid(k))

# softmax
print(torch.softmax(k, dim=0))

# relu
print(torch.relu(k))

tensor([[0.6931, 1.9459, 2.1972],
        [0.6931, 1.3863, 1.7918]])
tensor([[2.0000, 2.0000, 1.0000],
        [1.0000, 1.4142, 2.0000],
        [2.6458, 1.4142, 2.2361]])

tensor([[0.8808, 0.9991, 0.9999],
        [0.8808, 0.9820, 0.9975]])
tensor([[0.5000, 0.9526, 0.9526],
        [0.5000, 0.0474, 0.0474]])
tensor([[2., 7., 9.],
        [2., 4., 6.]])


## Inplace Operations

In [91]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2499, 0.3206, 0.9753],
        [0.7582, 0.6688, 0.2651]])
tensor([[0.2336, 0.5057, 0.5688],
        [0.0634, 0.8993, 0.2732]])


In [93]:
print(m.add_(n))   # Adding _ after function work same as inplace in pandas

tensor([[0.7172, 1.3320, 2.1129],
        [0.8849, 2.4674, 0.8116]])


## Copying a Tensor

In [94]:
a = torch.rand(2,3)
a

tensor([[0.3397, 0.1879, 0.5534],
        [0.2682, 0.9556, 0.9761]])

In [96]:
b = a.clone()
b

tensor([[0.3397, 0.1879, 0.5534],
        [0.2682, 0.9556, 0.9761]])

## Tensor Indexing & Slicing  & Reshaping

In [ ]:
a=torch.randint(low=0,high=100,size=(5,6))
print(a)

tensor([[50, 62, 37, 92, 54, 93],
        [62, 23, 92, 41, 98,  6],
        [ 5, 34, 21, 41, 13,  9],
        [14, 27, 76, 66, 95, 61],
        [44, 82, 36, 86, 39, 77]])


In [115]:
# Access single element
print(a[1,4])

# Row access
print(a[0])

# Column access
print(a[:,4])

# Slicing
print(a[:,3:])

tensor(98)
tensor([50, 62, 37, 92, 54, 93])
tensor([54, 98, 13, 95, 39])
tensor([[92, 54, 93],
        [41, 98,  6],
        [41, 13,  9],
        [66, 95, 61],
        [86, 39, 77]])


In [119]:
a = torch.tensor([[2., 4.],
                  [6., 8.]])

# 1. Get second column
# 2. Add 10 to all elements
# 3. Compute row-wise mean
# 4. Find max of each column

print(a[:,1])
print(a+10)
print(torch.mean(a,dim=1))
max,index=torch.max(a,dim=0)
print(max)

tensor([4., 8.])
tensor([[12., 14.],
        [16., 18.]])
tensor([3., 7.])
tensor([6., 8.])


In [ ]:
# Reshaping Tensors

# (1) View()  :- Same numbers, different shape, no copy

a=torch.randint(low=0,high=100,size=(3,4))
print(a)
print(a.shape)

print(a.view(2,6))
print()

print(a.view(-1))     # -1 for flattening the tensor

tensor([[87, 81, 93, 16],
        [ 9, 67, 50, 41],
        [80, 88, 85, 91]])
torch.Size([3, 4])
tensor([[87, 81, 93, 16,  9, 67],
        [50, 41, 80, 88, 85, 91]])

tensor([87, 81, 93, 16,  9, 67, 50, 41, 80, 88, 85, 91])


In [129]:
print(a.reshape(-1))

print(a.reshape(4,3))

tensor([87, 81, 93, 16,  9, 67, 50, 41, 80, 88, 85, 91])
tensor([[87, 81, 93],
        [16,  9, 67],
        [50, 41, 80],
        [88, 85, 91]])


## Autograd 

Step 1 : Make requires_grad=True (default=False) --> PyTorch starts tracking everything done with tensor.

Step 2 : backward() --> computes gradients of the final scalar output.

Step 3 : x.grad  --> stores gradient value and  Only leaf tensors have .grad .

In [ ]:
x = torch.tensor(2.0, requires_grad=True)
w = torch.tensor(3.0, requires_grad=True)

y = w * x
y.backward()

print(x.grad)
print(w.grad)


tensor(3.)
tensor(2.)


## Create Simple Neural Network

In [196]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [197]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [198]:
df.shape

(569, 33)

In [199]:
df.drop(["id", "Unnamed: 32"], axis=1, inplace=True)

In [200]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [201]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [202]:
y_train

423    B
264    M
551    B
166    B
23     M
      ..
110    B
436    B
270    B
247    B
371    B
Name: diagnosis, Length: 455, dtype: object

In [203]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [204]:
###  Numpy arrays to PyTorch tensors

X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [205]:
print(X_train_tensor.shape)

torch.Size([455, 30])


In [206]:
class SimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


In [207]:
learning_rate = 0.1
epochs = 25

In [211]:
model = SimpleNN(X_train_tensor)

for epoch in range(epochs):

    # Forward Pass
    y_pred = model.forward(X_train_tensor)

    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # Backpropagation
    loss.backward()

    # Update Paramter
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    
    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 3.2776469102249477
Epoch: 2, Loss: 3.141150639584516
Epoch: 3, Loss: 2.9990383828865235
Epoch: 4, Loss: 2.851887486907059
Epoch: 5, Loss: 2.7014257343107073
Epoch: 6, Loss: 2.546268684670367
Epoch: 7, Loss: 2.3842911593426357
Epoch: 8, Loss: 2.2177592890342903
Epoch: 9, Loss: 2.05450763671731
Epoch: 10, Loss: 1.8973834122124273
Epoch: 11, Loss: 1.7455816018931074
Epoch: 12, Loss: 1.6006551135472837
Epoch: 13, Loss: 1.466194835917548
Epoch: 14, Loss: 1.3411596434599757
Epoch: 15, Loss: 1.2302894217792384
Epoch: 16, Loss: 1.128721461144933
Epoch: 17, Loss: 1.0443849226960973
Epoch: 18, Loss: 0.9766286759212675
Epoch: 19, Loss: 0.9238821348070851
Epoch: 20, Loss: 0.8838505500881418
Epoch: 21, Loss: 0.8538670447852559
Epoch: 22, Loss: 0.8313285736925021
Epoch: 23, Loss: 0.8140389192754139
Epoch: 24, Loss: 0.8003438270087248
Epoch: 25, Loss: 0.7890937607255166


In [213]:
model.bias

tensor([-0.1735], dtype=torch.float64, requires_grad=True)

In [212]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5761772990226746


## torch.nn  (PyTorch’s neural network toolbox.)

It provides:

Layers (Linear, Conv, LSTM, etc.)

Activation functions (ReLU, Sigmoid…)

Loss functions (MSE, CrossEntropy…)

The base class nn.Module (heart of PyTorch models)

👉 Every neural network in PyTorch is a class that inherits from nn.Module.

In [2]:
import torch
import torch.nn as nn

In [18]:
class SimpleNNModule(nn.Module):

    def __init__(self,features):
        super().__init__()
        self.liner=nn.Linear(features,1)
        self.sigmoid=nn.Sigmoid()
    
    def forward(self,features):
        return self.sigmoid(self.liner(features))

In [19]:
X=torch.rand(10,5)

model=SimpleNNModule(X.shape[1])
print(model)
model(X)

SimpleNNModule(
  (liner): Linear(in_features=5, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


tensor([[0.5877],
        [0.6615],
        [0.6608],
        [0.6406],
        [0.6741],
        [0.6592],
        [0.6361],
        [0.7058],
        [0.6264],
        [0.6018]], grad_fn=<SigmoidBackward0>)

In [20]:
model.liner.weight

Parameter containing:
tensor([[-0.1940,  0.1710,  0.4353, -0.1112,  0.0650]], requires_grad=True)

In [21]:
model.liner.bias

Parameter containing:
tensor([0.4038], requires_grad=True)

In [22]:
class SimpleNNModule(nn.Module):

    def __init__(self,features):
        super().__init__()
        self.layer1=nn.Linear(features,3)
        self.relu=nn.ReLU()
        self.layer2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
    
    def forward(self,features):

        out=self.layer1(features)
        out=self.relu(out)
        out=self.layer2(out)
        out=self.sigmoid(out)

        return out

In [26]:
features=torch.rand(10,5)
model = SimpleNNModule(features.shape[1])
y_pred=model(features)
print(y_pred)
print()
print(model.layer1.weight)
print()
print(model.layer2.weight)

tensor([[0.4132],
        [0.4194],
        [0.4323],
        [0.4196],
        [0.4320],
        [0.4115],
        [0.4099],
        [0.4037],
        [0.4135],
        [0.4031]], grad_fn=<SigmoidBackward0>)

Parameter containing:
tensor([[ 0.1533,  0.4285,  0.2342, -0.0958, -0.3347],
        [-0.2799,  0.2029,  0.3545,  0.0648, -0.2116],
        [ 0.4255,  0.0476, -0.1195,  0.2930,  0.1210]], requires_grad=True)

Parameter containing:
tensor([[-0.2522,  0.1037, -0.0190]], requires_grad=True)


In [29]:
class MySimpleNNModule(nn.Module):

    def __init__(self,features):
        super().__init__()
        self.network=nn.Sequential(nn.Linear(features,3),
                                   nn.ReLU(),
                                   nn.Linear(3,1),
                                   nn.Sigmoid()
                                   )
    
    def forward(self,features):
        return self.network(features)


In [34]:
features=torch.rand(10,5)
model = MySimpleNNModule(features.shape[1])
y_pred=model(features)
print(y_pred)
print()
print("First layer weights:\n", model.network[0].weight)
print("First layer bias:\n", model.network[0].bias)

print("\nSecond layer weights:\n", model.network[2].weight)
print("Second layer bias:\n", model.network[2].bias)


tensor([[0.5049],
        [0.5048],
        [0.5059],
        [0.5040],
        [0.5040],
        [0.5057],
        [0.5056],
        [0.5032],
        [0.5060],
        [0.5044]], grad_fn=<SigmoidBackward0>)

First layer weights:
 Parameter containing:
tensor([[-0.0243,  0.4432, -0.2669, -0.0486, -0.2176],
        [-0.0434,  0.2242, -0.1967, -0.0353,  0.1322],
        [-0.1367,  0.1824,  0.3731,  0.3648,  0.2121]], requires_grad=True)
First layer bias:
 Parameter containing:
tensor([-0.3033, -0.3036, -0.1357], requires_grad=True)

Second layer weights:
 Parameter containing:
tensor([[ 0.1158,  0.1098, -0.0251]], requires_grad=True)
Second layer bias:
 Parameter containing:
tensor([0.0281], requires_grad=True)


## torch.nn on Real World Dataset

In [228]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [229]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [230]:
df.drop(["id","Unnamed: 32"],axis=1, inplace=True)

In [231]:
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,1:],df.iloc[:, 0], test_size=0.2)

In [232]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [233]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [234]:
X_train_tensor=torch.from_numpy(X_train)
X_test_tensor=torch.from_numpy(X_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

# Ensure that Always datatype of all tensor are same 
# nn.Linear(...)   → parameters are float32 by default
# torch.from_numpy(X_train) → float64

X_train_tensor=X_train_tensor.to(torch.float32)
X_test_tensor=X_test_tensor.to(torch.float32)
y_train_tensor=y_train_tensor.to(torch.float32)
y_test_tensor=y_test_tensor.to(torch.float32)

y_train_tensor = y_train_tensor.view(-1, 1)   #  ypred shape is [455,1] but y_train_tensor shape is [455,] so we need to convert them in same shape  (-1,1)-->Columns Vector and -1 means: “PyTorch, you figure out this dimension for me.”
y_test_tensor = y_test_tensor.view(-1, 1)


In [235]:
class NeuralNetwork(nn.Module):

    def __init__(self,features):

        super().__init__()
        self.neural_network=nn.Sequential(
            nn.Linear(features,5),
            nn.ReLU(),
            nn.Linear(5,1),
            # nn.Sigmoid()            # We are not using Sigmoid here because BCEWithLogitsLoss already applies Sigmoid internally.
        )

    def forward(self,features):
        return self.neural_network(features)

In [236]:
model = NeuralNetwork(X_train_tensor.shape[1])

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
loss_fn = nn.BCEWithLogitsLoss()

for epoch in range(100):

    optimizer.zero_grad()      #  Reset Gradients
    y_pred = model(X_train_tensor)   # Forward Pass
    loss = loss_fn(y_pred, y_train_tensor)  # Loss
    loss.backward()           # Backpropagation
    optimizer.step()           # Update

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item():.4f}")



Epoch 0, Loss: 0.6690
Epoch 10, Loss: 0.4015
Epoch 20, Loss: 0.2219
Epoch 30, Loss: 0.1449
Epoch 40, Loss: 0.1081
Epoch 50, Loss: 0.0887
Epoch 60, Loss: 0.0760
Epoch 70, Loss: 0.0675
Epoch 80, Loss: 0.0613
Epoch 90, Loss: 0.0567


In [237]:
def binary_accuracy(logits, y_true):
    probs = torch.sigmoid(logits)
    preds = (probs >= 0.5).float()
    acc = (preds == y_true).float().mean()
    return acc


In [238]:
model.eval()
with torch.no_grad():
    train_logits = model(X_train_tensor)
    train_acc = binary_accuracy(train_logits, y_train_tensor)

print(f"Train Accuracy: {train_acc.item()*100:.2f}%")


Train Accuracy: 98.46%


In [239]:
model.eval()
with torch.no_grad():
    test_logits = model(X_test_tensor)
    test_acc = binary_accuracy(test_logits, y_test_tensor)

print(f"Test Accuracy: {test_acc.item()*100:.2f}%")


Test Accuracy: 98.25%
